#!/usr/bin/env bash
#
# remove-old-zen.sh — DESTRUCTIVE. Retire the abandoned first attempt at
# packaging Zen Browser, so the new www-client/zen-bin::zen overlay is the only
# Zen packaging left on this system.
#
# WHAT IT REMOVES:
#   * /var/db/repos/local/www-client/zen              (old source-build ebuild)
#   * /var/db/repos/local/www-client/zen-browser-bin  (old binary ebuild)
#     -> everything else in ::local, including gui-wm/niri, is left ALONE.
#
# WHAT IT EDITS (single-line, exact-match removals only — these files hold a
# lot of unrelated, autogenerated content):
#   * /etc/portage/package.use/zen
#       remove  'www-client/zen pgo'
#       keep    '>=media-libs/libpng-1.6.58 apng'
#       keep    '>=x11-base/xorg-server-21.1.22 xvfb'
#       keep    ~200 lines of python dependency USE flags
#   * /etc/portage/package.accept_keywords/zen-browser
#       remove  'www-client/zen-browser-bin ~amd64'
#       NOTE: on this system that file contains ONLY that line, so it ends up
#             empty. It is left in place (empty), not deleted.
#
# It also looks for leftovers from the old source build (~/zen-overlay-staging,
# ~/builds/zen, /var/cache/distfiles/zen-*-engine.tar.xz) and offers to remove
# them if they still exist.
#
# Every file it edits is backed up first as <file>.bak-YYYYmmddHHMMSS.
#
# USAGE:
#   ./scripts/remove-old-zen.sh              # DRY RUN (the default) — changes nothing
#   ./scripts/remove-old-zen.sh --dry-run    # same thing, explicitly
#   ./scripts/remove-old-zen.sh --execute    # for real: warns, sleeps, asks you to type 'yes'
#   ./scripts/remove-old-zen.sh --help
#
# Run the dry run first. Always.
#
set -euo pipefail

# ---------------------------------------------------------------- helpers ---
if [[ -t 1 ]]; then
	C_RESET=$'\033[0m'; C_INFO=$'\033[1;36m'; C_OK=$'\033[1;32m'
	C_WARN=$'\033[1;33m'; C_ERR=$'\033[1;31m'; C_DIM=$'\033[2m'
else
	C_RESET=''; C_INFO=''; C_OK=''; C_WARN=''; C_ERR=''; C_DIM=''
fi

say()  { printf '%s==>%s %s\n'    "$C_INFO" "$C_RESET" "$*"; }
ok()   { printf '%s  ok%s %s\n'   "$C_OK"   "$C_RESET" "$*"; }
warn() { printf '%swarn:%s %s\n'  "$C_WARN" "$C_RESET" "$*" >&2; }
die()  { printf '%sfatal:%s %s\n' "$C_ERR"  "$C_RESET" "$*" >&2; exit 1; }
skip() { printf '%s  --%s %s\n'   "$C_DIM"  "$C_RESET" "$*"; }

as_root() {
	if [[ ${EUID} -eq 0 ]]; then
		"$@"
	else
		sudo "$@"
	fi
}

usage() {
	cat <<EOF
Usage: ${0##*/} [--dry-run | --execute] [-h|--help]

  (no options)  dry run — print everything that WOULD happen, change nothing
  --dry-run     the same, stated explicitly
  --execute     actually do it; warns, sleeps 3s, then requires you to type 'yes'
  -h, --help    this help

Removes the abandoned www-client/zen and www-client/zen-browser-bin packages
from the ::local overlay and their two leftover /etc/portage lines.
EOF
}

# ------------------------------------------------------------- arguments ----
DRY_RUN=1

while [[ $# -gt 0 ]]; do
	case "$1" in
		-h|--help)  usage; exit 0 ;;
		-n|--dry-run) DRY_RUN=1; shift ;;
		--execute|--apply|--yes-really) DRY_RUN=0; shift ;;
		*) usage >&2; die "unknown argument: $1" ;;
	esac
done

STAMP=$(date +%Y%m%d%H%M%S)

# ------------------------------------------------------------- the targets --
LOCAL_ZEN=/var/db/repos/local/www-client/zen
LOCAL_ZEN_BIN=/var/db/repos/local/www-client/zen-browser-bin

USE_FILE=/etc/portage/package.use/zen
USE_LINE='www-client/zen pgo'

KW_FILE=/etc/portage/package.accept_keywords/zen-browser
KW_LINE='www-client/zen-browser-bin ~amd64'

STAGING_DIR="${HOME}/zen-overlay-staging"
BUILD_DIR="${HOME}/builds/zen"

# Old engine tarballs from the source-build attempt.
mapfile -t ENGINE_TARBALLS < <(
	find /var/cache/distfiles -maxdepth 1 -type f -name 'zen-*-engine.tar.xz' 2>/dev/null | sort
)

# ------------------------------------------------------------- the report ---
printf '\n'
printf '%s================ remove-old-zen.sh ================%s\n' "$C_ERR" "$C_RESET"
if [[ ${DRY_RUN} -eq 1 ]]; then
	printf '%sMODE: DRY RUN — nothing will be changed.%s\n' "$C_OK" "$C_RESET"
else
	printf '%sMODE: EXECUTE — this will DELETE and EDIT the items below.%s\n' "$C_ERR" "$C_RESET"
fi
printf '\n'

say "directories that will be REMOVED (recursively, as root):"
for d in "${LOCAL_ZEN}" "${LOCAL_ZEN_BIN}"; do
	if [[ -e ${d} ]]; then
		printf '    %sDELETE%s %s\n' "$C_ERR" "$C_RESET" "${d}"
		find "${d}" -maxdepth 2 -mindepth 1 -printf '             %p\n' 2>/dev/null | head -n 20
	else
		skip "${d} (does not exist — nothing to do)"
	fi
done

printf '\n'
say "single lines that will be REMOVED from config files:"

check_line() {
	# $1 = file, $2 = exact line. echoes "present"/"absent"/"nofile"
	if [[ ! -f $1 ]]; then printf 'nofile\n'; return 0; fi
	if grep -qxF -- "$2" "$1"; then printf 'present\n'; else printf 'absent\n'; fi
}

USE_STATE=$(check_line "${USE_FILE}" "${USE_LINE}")
KW_STATE=$(check_line "${KW_FILE}" "${KW_LINE}")

report_line() {
	local file=$1 line=$2 state=$3
	case "${state}" in
		present)
			printf '    %sREMOVE%s %s\n' "$C_ERR" "$C_RESET" "${file}"
			printf '             line: %s\n' "${line}"
			printf '             (backup: %s.bak-%s)\n' "${file}" "${STAMP}"
			printf '             file keeps %s of its %s lines\n' \
				"$(grep -vxFc -- "${line}" "${file}" || true)" "$(wc -l < "${file}")"
			if [[ "$(grep -vxFc -- "${line}" "${file}" || true)" == "0" ]]; then
				printf '             %sthis file becomes EMPTY (kept in place, not deleted)%s\n' \
					"$C_WARN" "$C_RESET"
			fi
			;;
		absent)  skip "${file}: line '${line}' not present — nothing to do" ;;
		nofile)  skip "${file}: file does not exist — nothing to do" ;;
	esac
}

report_line "${USE_FILE}" "${USE_LINE}" "${USE_STATE}"
report_line "${KW_FILE}"  "${KW_LINE}"  "${KW_STATE}"

if [[ ${USE_STATE} == present ]]; then
	printf '\n    %sThese lines in %s are KEPT:%s\n' "$C_OK" "${USE_FILE}" "$C_RESET"
	grep -nE '^(>=media-libs/libpng-|>=x11-base/xorg-server-)' "${USE_FILE}" \
		| sed 's/^/             /' || true
	printf '             ... plus %s further unrelated lines\n' \
		"$(( $(wc -l < "${USE_FILE}") - 3 ))"
fi

printf '\n'
say "leftovers from the old source build:"
LEFTOVERS=()
for p in "${STAGING_DIR}" "${BUILD_DIR}" "${ENGINE_TARBALLS[@]:-}"; do
	[[ -n ${p} ]] || continue
	if [[ -e ${p} ]]; then
		LEFTOVERS+=("${p}")
		printf '    %sFOUND%s  %s  (%s)\n' "$C_WARN" "$C_RESET" "${p}" "$(du -sh "${p}" 2>/dev/null | cut -f1)"
	else
		skip "${p} (absent)"
	fi
done
if [[ ${#LEFTOVERS[@]} -eq 0 ]]; then
	ok "no source-build leftovers found — nothing extra to clean"
fi

printf '\n'
say "NOT touched by this script:"
printf '    /var/db/repos/local/gui-wm/niri\n'
printf '    /var/db/repos/local/{metadata,profiles,scripts}\n'
printf '    every other line of %s\n' "${USE_FILE}"
printf '    every other line of %s\n' "${KW_FILE}"
printf '\n'

# --------------------------------------------------------- the dry-run exit --
if [[ ${DRY_RUN} -eq 1 ]]; then
	printf '%s=================================================%s\n' "$C_ERR" "$C_RESET"
	ok "dry run complete — nothing was changed."
	printf '\nRe-run with %s--execute%s to actually perform the above.\n' "$C_WARN" "$C_RESET"
	exit 0
fi

# ------------------------------------------------------ the confirmation -----
printf '%s=================================================%s\n' "$C_ERR" "$C_RESET"
printf '%s!! WARNING !!%s  The deletions above are IRREVERSIBLE.\n' "$C_ERR" "$C_RESET"
printf '%s%s%s\n' "$C_ERR" \
	'              Edited files get a .bak-* copy; deleted directories do NOT.' \
	"$C_RESET"
printf '%s              Read the list above before answering.%s\n' "$C_ERR" "$C_RESET"
printf '\n'

sleep 3

if [[ ! -t 0 ]]; then
	die "stdin is not a terminal — refusing to run destructively without an interactive confirmation"
fi

printf 'Type %syes%s (exactly) to proceed, anything else to abort: ' "$C_WARN" "$C_RESET"
read -r CONFIRM || CONFIRM=""

if [[ ${CONFIRM} != "yes" ]]; then
	printf '\n'
	ok "aborted — nothing was changed."
	exit 1
fi
printf '\n'

# ---------------------------------------------------------- 1. directories ---
say "removing old ::local packages"
REMOVED_DIRS=()
for d in "${LOCAL_ZEN}" "${LOCAL_ZEN_BIN}"; do
	if [[ -e ${d} ]]; then
		as_root rm -rf -- "${d}"
		REMOVED_DIRS+=("${d}")
		ok "removed ${d}"
	else
		skip "${d} already gone"
	fi
done

# -------------------------------------------------------- 2. line removal ----
EDITED_FILES=()
EMPTIED_FILES=()

remove_exact_line() {
	local file=$1 line=$2
	local tmp backup before after

	if [[ ! -f ${file} ]]; then
		warn "${file} does not exist — skipping"
		return 0
	fi
	if ! grep -qxF -- "${line}" "${file}"; then
		warn "${file}: line '${line}' not found — skipping (already cleaned?)"
		return 0
	fi

	backup="${file}.bak-${STAMP}"
	as_root cp -a -- "${file}" "${backup}"
	ok "backed up ${file} -> ${backup}"

	before=$(wc -l < "${file}")

	tmp=$(mktemp)
	# grep -v exits 1 when nothing is left; that is not an error here.
	grep -vxF -- "${line}" "${file}" > "${tmp}" || true

	as_root cp --no-preserve=mode,ownership -- "${tmp}" "${file}"
	as_root chmod --reference="${backup}" -- "${file}"
	as_root chown --reference="${backup}" -- "${file}"
	rm -f -- "${tmp}"

	after=$(wc -l < "${file}")
	EDITED_FILES+=("${file}")
	ok "${file}: ${before} -> ${after} lines (removed '${line}')"

	if [[ ! -s ${file} ]]; then
		EMPTIED_FILES+=("${file}")
		warn "${file} is now EMPTY (left in place on purpose, not deleted)"
	fi
}

say "editing portage config"
remove_exact_line "${USE_FILE}" "${USE_LINE}"
remove_exact_line "${KW_FILE}"  "${KW_LINE}"

# Prove the keepers survived.
if [[ -f ${USE_FILE} ]]; then
	for keep in '>=media-libs/libpng-1.6.58 apng' '>=x11-base/xorg-server-21.1.22 xvfb'; do
		if grep -qxF -- "${keep}" "${USE_FILE}"; then
			ok "kept: ${keep}"
		else
			warn "expected to keep '${keep}' in ${USE_FILE} but it is not there"
		fi
	done
fi

# ----------------------------------------------------------- 3. leftovers ----
CLEANED_LEFTOVERS=()
if [[ ${#LEFTOVERS[@]} -gt 0 ]]; then
	printf '\n'
	say "source-build leftovers found:"
	printf '    %s\n' "${LEFTOVERS[@]}"
	printf 'Remove these too? Type %syes%s to remove, anything else to keep them: ' \
		"$C_WARN" "$C_RESET"
	read -r CONFIRM2 || CONFIRM2=""
	if [[ ${CONFIRM2} == "yes" ]]; then
		for p in "${LEFTOVERS[@]}"; do
			if [[ ${p} == /var/cache/distfiles/* ]]; then
				as_root rm -f -- "${p}"
			else
				rm -rf -- "${p}"
			fi
			CLEANED_LEFTOVERS+=("${p}")
			ok "removed ${p}"
		done
	else
		skip "leftovers kept"
	fi
fi

# ------------------------------------------------------------- 4. summary ----
printf '\n'
printf '%s===================== summary =====================%s\n' "$C_INFO" "$C_RESET"

if [[ ${#REMOVED_DIRS[@]} -gt 0 ]]; then
	printf 'Removed package dirs:\n'; printf '  %s\n' "${REMOVED_DIRS[@]}"
else
	printf 'Removed package dirs: none (already gone)\n'
fi

if [[ ${#EDITED_FILES[@]} -gt 0 ]]; then
	printf 'Edited config files (backups kept as *.bak-%s):\n' "${STAMP}"
	printf '  %s\n' "${EDITED_FILES[@]}"
else
	printf 'Edited config files: none\n'
fi

if [[ ${#EMPTIED_FILES[@]} -gt 0 ]]; then
	printf 'Now empty (kept anyway):\n'; printf '  %s\n' "${EMPTIED_FILES[@]}"
fi

if [[ ${#CLEANED_LEFTOVERS[@]} -gt 0 ]]; then
	printf 'Removed leftovers:\n'; printf '  %s\n' "${CLEANED_LEFTOVERS[@]}"
fi

printf '\n'
if [[ ${#REMOVED_DIRS[@]} -gt 0 ]]; then
	say "the ::local overlay changed, so refresh portage's metadata cache:"
	printf '  sudo emerge --regen\n'
	printf '  (or just let the next emerge rebuild it lazily — --regen is the tidy option)\n'
else
	ok "nothing structural changed — no 'emerge --regen' needed."
fi

printf '\nSanity check afterwards:\n'
printf '  emerge -s %%^zen\n'
printf '  emerge -pv www-client/zen-bin\n'
